/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Pre-compiled data generated by NexVora Content-Processing Engine
import { ProcessingChunk, ProcessingReport, FailedUrlRecord, CategoryIndexChunk } from './types.ts';

export const PRECOMPILED_CHUNKS: ProcessingChunk[] = [
  {
    "chunkId": "chunk-001",
    "filename": "chunk-001.json",
    "documentCount": 6,
    "totalBytes": 5886,
    "createdAt": "2026-09-24T04:34:52.824Z",
    "documents": [
      {
        "id": "doc-developer_mozilla_org-u8z5d0",
        "url": "https://developer.mozilla.org/en-US/docs/Web/JavaScript?utm_source=newsletter&utm_medium=email",
        "canonicalUrl": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        "domain": "developer.mozilla.org",
        "title": "JavaScript | MDN Web Docs",
        "description": "JavaScript (JS) is a lightweight interpreted or just-in-time compiled programming language with first-class functions for web development.",
        "headings": {
          "h1": [
            "JavaScript (JS) Overview"
          ],
          "h2": [
            "Core Language Features",
            "Ecosystem & Tooling"
          ],
          "h3": []
        },
        "mainText": "JavaScript (JS) Overview\n\nJavaScript is a scripting or programming language that allows you to implement complex features on web pages. Whenever a web page does more than just sit there and display static information, JavaScript is likely involved.\n\nCore Language Features\n\nStandardized via ECMAScript, JavaScript features modern asynchronous syntax (async/await), typed arrays, modular imports, closures, and object prototypes for scalable frontend and backend runtime development.\n\nModern developers write TypeScript and JavaScript using package bundlers, Vite, Node.js, and frameworks like React to build interactive client-side web applications.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.84,
        "categorySignals": [
          "domain:developer.mozilla.org",
          "url_pattern:\\/docs\\/",
          "url_pattern:\\/developer",
          "url_pattern:\\/javascript",
          "title:javascript",
          "heading:javascript",
          "desc:programming",
          "desc:javascript",
          "body:javascript(5)"
        ],
        "contentLengthBytes": 1235,
        "wordCount": 86,
        "statusCode": 200,
        "fetchTimeMs": 24,
        "processedAt": "2026-09-24T04:34:51.957Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      },
      {
        "id": "doc-react_dev-30482j",
        "url": "https://react.dev/blog/2024/12/05/react-19?ref=hackernews",
        "canonicalUrl": "https://react.dev/blog/2024/12/05/react-19",
        "domain": "react.dev",
        "title": "React 19 is now stable – React Official Blog",
        "description": "React 19 is now available on npm! Featuring Actions, Server Components, Document Metadata hooks, and asset preloading for frontend developers.",
        "headings": {
          "h1": [
            "React 19 Release Notes"
          ],
          "h2": [
            "What is new in React 19?",
            "Upgrading to React 19"
          ],
          "h3": []
        },
        "mainText": "React 19 Release Notes\n\nIn our React 19 release announcement, we shared that React 19 brings Actions, useActionState, Server Functions, ref as a prop, and automatic hydration improvements.\n\nWhat is new in React 19?\n\nActions handle pending states, optimistic updates, and form submissions natively. The new React compiler automates memoization for high performance user interfaces.\n\nUpgrading to React 19\n\nTo upgrade your web package dependencies, run npm install react@latest react-dom@latest. Most React 18 patterns are backwards compatible.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.81,
        "categorySignals": [
          "domain:react.dev",
          "url_pattern:\\/react",
          "title:react",
          "heading:react",
          "desc:react",
          "desc:npm",
          "desc:frontend",
          "body:react(8)"
        ],
        "contentLengthBytes": 1050,
        "wordCount": 77,
        "statusCode": 200,
        "fetchTimeMs": 39,
        "processedAt": "2026-09-24T04:34:52.000Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      },
      {
        "id": "doc-rust_lang_org-tjztg8",
        "url": "https://www.rust-lang.org/learn",
        "canonicalUrl": "https://www.rust-lang.org/learn",
        "domain": "rust-lang.org",
        "title": "Learn Rust – Rust Programming Language",
        "description": "Empowering everyone to build reliable and efficient software. Learn Rust through interactive tutorials, the Rust Book, and compiler borrow checker guides.",
        "headings": {
          "h1": [
            "Learn the Rust Programming Language"
          ],
          "h2": [
            "Read the Book",
            "Rustlings Course"
          ],
          "h3": []
        },
        "mainText": "Learn the Rust Programming Language\n\nRust offers memory safety without garbage collection, concurrency without data races, and zero-cost abstractions for systems programming.\n\nAffectionately nicknamed The Book, The Rust Programming Language gives you an overview of language syntax, ownership rules, lifetimes, and cargo package management.\n\nSmall exercises to get you used to reading and writing Rust code, fixing compiler errors, and understanding pattern matching.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.65,
        "categorySignals": [
          "domain:rust-lang.org",
          "title:programming",
          "title:rust",
          "heading:programming",
          "heading:rust",
          "desc:rust",
          "desc:compiler",
          "body:programming(3)",
          "body:rust(4)"
        ],
        "contentLengthBytes": 997,
        "wordCount": 63,
        "statusCode": 200,
        "fetchTimeMs": 23,
        "processedAt": "2026-09-24T04:34:52.024Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      },
      {
        "id": "doc-bun_sh-cddiid",
        "url": "https://bun.sh/docs",
        "canonicalUrl": "https://bun.sh/docs",
        "domain": "bun.sh",
        "title": "Bun Documentation – Fast JavaScript Runtime & Package Manager",
        "description": "Bun is an all-in-one JavaScript runtime, bundler, test runner, and package manager written in Zig with native speed and Node.js compatibility.",
        "headings": {
          "h1": [
            "Bun All-in-One JavaScript Runtime"
          ],
          "h2": [
            "Package Manager Speed",
            "Bundling & Serving"
          ],
          "h3": []
        },
        "mainText": "Bun All-in-One JavaScript Runtime\n\nBun was built from scratch using Zig and JavaScriptCore to focus on performance, developer ergonomics, and native TypeScript execution without transpilation steps.\n\nPackage Manager Speed\n\nBun installs npm packages orders of magnitude faster by utilizing system copy_file_range and hardlinks.\n\nBun includes a blazing-fast native bundler and HTTP web server module capable of handling millions of requests per second.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.89,
        "categorySignals": [
          "domain:bun.sh",
          "title:javascript",
          "title:package",
          "title:runtime",
          "title:bun",
          "heading:javascript",
          "heading:package",
          "heading:runtime",
          "heading:bun",
          "desc:javascript"
        ],
        "contentLengthBytes": 966,
        "wordCount": 62,
        "statusCode": 200,
        "fetchTimeMs": 40,
        "processedAt": "2026-09-24T04:34:52.065Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      },
      {
        "id": "doc-vite_dev-s4xs6s",
        "url": "https://vite.dev/guide/",
        "canonicalUrl": "https://vite.dev/guide/",
        "domain": "vite.dev",
        "title": "Getting Started | Vite Next Generation Frontend Tooling",
        "description": "Vite is a modern build tool that aims to provide a faster and leaner development experience for modern web projects using native ES modules.",
        "headings": {
          "h1": [
            "Getting Started with Vite"
          ],
          "h2": [
            "Lightning Fast Cold Starts"
          ],
          "h3": []
        },
        "mainText": "Getting Started with Vite\n\nVite consists of two major parts: a dev server that provides rich feature enhancements over native ES modules, and a build command that bundles your code with Rollup.\n\nLightning Fast Cold Starts\n\nBy pre-bundling dependencies with esbuild and serving source code over native ESM, Vite eliminates server bundling delays during development.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.77,
        "categorySignals": [
          "domain:vite.dev",
          "title:vite",
          "title:frontend",
          "heading:vite",
          "desc:vite",
          "body:code(2)",
          "body:vite(3)"
        ],
        "contentLengthBytes": 832,
        "wordCount": 55,
        "statusCode": 200,
        "fetchTimeMs": 22,
        "processedAt": "2026-09-24T04:34:52.088Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      },
      {
        "id": "doc-tailwindcss_com-0cja4g",
        "url": "https://tailwindcss.com/docs/v4-upgrade-guide",
        "canonicalUrl": "https://tailwindcss.com/docs/v4-upgrade-guide",
        "domain": "tailwindcss.com",
        "title": "Upgrade Guide to Tailwind CSS v4 – Tailwind Documentation",
        "description": "Comprehensive guide for migrating your frontend styles to Tailwind CSS v4 featuring the new high-speed Rust-powered engine and CSS-first configuration.",
        "headings": {
          "h1": [
            "Upgrading to Tailwind CSS v4"
          ],
          "h2": [
            "New Engine Architecture"
          ],
          "h3": []
        },
        "mainText": "Upgrading to Tailwind CSS v4\n\nTailwind CSS v4 is a ground-up rewrite of the framework, designed for speed and built using a new unified CSS-first configuration model.\n\nNew Engine Architecture\n\nBuilt with Lightning CSS, Tailwind v4 compiles stylesheets up to 10x faster with a fraction of memory usage.",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.45,
        "categorySignals": [
          "url_pattern:\\/docs\\/",
          "desc:frontend"
        ],
        "contentLengthBytes": 806,
        "wordCount": 48,
        "statusCode": 200,
        "fetchTimeMs": 36,
        "processedAt": "2026-09-24T04:34:52.125Z",
        "chunkId": "chunk-001",
        "retryCount": 0
      }
    ]
  },
  {
    "chunkId": "chunk-002",
    "filename": "chunk-002.json",
    "documentCount": 6,
    "totalBytes": 5073,
    "createdAt": "2026-09-24T04:34:52.824Z",
    "documents": [
      {
        "id": "doc-github_com-2sioca",
        "url": "https://github.com/torvalds/linux",
        "canonicalUrl": "https://github.com/torvalds/linux",
        "domain": "github.com",
        "title": "torvalds/linux: Linux kernel source tree – GitHub",
        "description": "Linux kernel source tree maintained by Linus Torvalds. The open source monolithic operating system kernel powering cloud servers, supercomputers, and mobile devices.",
        "headings": {
          "h1": [
            "Linux Kernel Source Repository"
          ],
          "h2": [
            "Subsystems & Architecture"
          ],
          "h3": []
        },
        "mainText": "Linux Kernel Source Repository\n\nLinux is a free software, open-source Unix-like operating system kernel created by Linus Torvalds in 1991. The codebase is primarily written in C with portions in Rust and assembly.\n\nSubsystems & Architecture\n\nIncludes memory management, process scheduling, virtual file system (VFS), networking stack, device drivers, and namespace isolation for Docker and Linux containers.",
        "language": "en",
        "category": "Technology",
        "categoryConfidence": 0.65,
        "categorySignals": [
          "url_pattern:\\/linux",
          "title:linux",
          "title:kernel",
          "heading:linux",
          "heading:kernel",
          "heading:architecture",
          "desc:cloud",
          "desc:linux",
          "desc:kernel",
          "desc_phrase:operating system"
        ],
        "contentLengthBytes": 906,
        "wordCount": 57,
        "statusCode": 200,
        "fetchTimeMs": 23,
        "processedAt": "2026-09-24T04:34:52.149Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      },
      {
        "id": "doc-sqlite_org-0n5f59",
        "url": "https://sqlite.org/arch.html",
        "canonicalUrl": "https://sqlite.org/arch.html",
        "domain": "sqlite.org",
        "title": "Architecture of SQLite – In-Process SQL Database Engine",
        "description": "Technical architecture and internal subsystems of SQLite: tokenizer, parser, code generator, virtual machine (VDBE), B-Tree, pager, and OS interface.",
        "headings": {
          "h1": [
            "The Architecture of SQLite"
          ],
          "h2": [
            "Virtual Database Engine (VDBE)"
          ],
          "h3": []
        },
        "mainText": "The Architecture of SQLite\n\nSQLite is structured into three main subsystems: the compiler subsystem (SQL frontend), the execution engine (virtual database engine VDBE), and the storage backend (B-tree and pager).\n\nVirtual Database Engine (VDBE)\n\nThe VDBE is a register-based virtual machine that executes bytecode instructions produced by the SQL parser and code generator to read or write database records.",
        "language": "en",
        "category": "Technology",
        "categoryConfidence": 0.8,
        "categorySignals": [
          "domain:sqlite.org",
          "title:database",
          "title:sql",
          "title:sqlite",
          "title:architecture",
          "heading:database",
          "heading:sqlite",
          "heading:architecture",
          "desc:sqlite",
          "desc:architecture"
        ],
        "contentLengthBytes": 891,
        "wordCount": 59,
        "statusCode": 200,
        "fetchTimeMs": 32,
        "processedAt": "2026-09-24T04:34:52.182Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      },
      {
        "id": "doc-kubernetes_io-n9zmsd",
        "url": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "canonicalUrl": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "domain": "kubernetes.io",
        "title": "What is Kubernetes? | Kubernetes Cloud Infrastructure",
        "description": "Kubernetes is an open-source container orchestration system for automating software deployment, scaling, and management of containerized applications.",
        "headings": {
          "h1": [
            "Introduction to Kubernetes Container Orchestration"
          ],
          "h2": [],
          "h3": []
        },
        "mainText": "Introduction to Kubernetes Container Orchestration\n\nKubernetes provides a framework to run distributed systems resiliently. It takes care of scaling and failover for your application, provides deployment patterns, and manages cluster hardware resources.",
        "language": "en",
        "category": "Technology",
        "categoryConfidence": 0.8,
        "categorySignals": [
          "domain:kubernetes.io",
          "url_pattern:\\/kubernetes",
          "title:cloud",
          "title:infrastructure",
          "title:kubernetes",
          "heading:kubernetes",
          "heading:container",
          "desc:software",
          "desc:kubernetes",
          "desc:container"
        ],
        "contentLengthBytes": 748,
        "wordCount": 32,
        "statusCode": 200,
        "fetchTimeMs": 41,
        "processedAt": "2026-09-24T04:34:52.224Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      },
      {
        "id": "doc-docs_docker_com-20mfff",
        "url": "https://docs.docker.com/get-started/overview/",
        "canonicalUrl": "https://docs.docker.com/get-started/overview/",
        "domain": "docs.docker.com",
        "title": "Docker Overview | Containerization Platform Architecture",
        "description": "Docker is an open platform for developing, shipping, and running applications using OS-level containerization for predictable environments.",
        "headings": {
          "h1": [
            "Docker Platform Overview"
          ],
          "h2": [],
          "h3": []
        },
        "mainText": "Docker Platform Overview\n\nDocker provides the ability to package and run an application in a loosely isolated environment called a container. The isolation and security allow you to run many containers simultaneously on a given host.",
        "language": "en",
        "category": "Technology",
        "categoryConfidence": 0.66,
        "categorySignals": [
          "domain:docker.com",
          "title:docker",
          "title:architecture",
          "heading:docker",
          "desc:docker",
          "body:docker(2)"
        ],
        "contentLengthBytes": 701,
        "wordCount": 36,
        "statusCode": 200,
        "fetchTimeMs": 39,
        "processedAt": "2026-09-24T04:34:52.264Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      },
      {
        "id": "doc-signal_org-6kh80a",
        "url": "https://signal.org/docs/specifications/doubleratchet/",
        "canonicalUrl": "https://signal.org/docs/specifications/doubleratchet/",
        "domain": "signal.org",
        "title": "The Double Ratchet Algorithm – Signal Cryptographic Protocol",
        "description": "Cryptographic specification of the Double Ratchet Algorithm: providing end-to-end encryption with forward secrecy and break-in recovery for messaging protocols.",
        "headings": {
          "h1": [
            "The Double Ratchet Cryptographic Algorithm"
          ],
          "h2": [],
          "h3": []
        },
        "mainText": "The Double Ratchet Cryptographic Algorithm\n\nThe Double Ratchet algorithm is used by two parties to exchange encrypted messages based on a shared secret key. The parties derive new keys for every message so that earlier keys cannot be calculated from later ones (forward secrecy).",
        "language": "en",
        "category": "Programming",
        "categoryConfidence": 0.42,
        "categorySignals": [
          "url_pattern:\\/docs\\/",
          "title:algorithm",
          "heading:algorithm",
          "desc:algorithm",
          "body:algorithm(2)"
        ],
        "contentLengthBytes": 782,
        "wordCount": 44,
        "statusCode": 200,
        "fetchTimeMs": 32,
        "processedAt": "2026-09-24T04:34:52.296Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      },
      {
        "id": "doc-webb_nasa_gov-z5ha8c",
        "url": "https://webb.nasa.gov/content/science/overview.html",
        "canonicalUrl": "https://webb.nasa.gov/content/science/overview.html",
        "domain": "webb.nasa.gov",
        "title": "Science Overview – James Webb Space Telescope – NASA",
        "description": "Explore the scientific mission of NASA",
        "headings": {
          "h1": [
            "NASA James Webb Space Telescope Science Mission"
          ],
          "h2": [
            "Infrared Astronomy & Deep Fields"
          ],
          "h3": []
        },
        "mainText": "NASA James Webb Space Telescope Science Mission\n\nThe James Webb Space Telescope (JWST) is the premier space observatory of the next decade, studying every phase in the history of our Universe from the first luminous glows after the Big Bang to the formation of solar systems capable of supporting life on planets like Earth.\n\nInfrared Astronomy & Deep Fields\n\nBecause the universe is expanding, light from the most distant cosmic objects shifts into infrared wavelengths. Webb's gold-coated mirrors capture deep cosmic fields.",
        "language": "en",
        "category": "Science",
        "categoryConfidence": 0.88,
        "categorySignals": [
          "domain:nasa.gov",
          "url_pattern:\\/science",
          "title:science",
          "title:space",
          "title:telescope",
          "title:nasa",
          "title_phrase:james webb",
          "heading:science",
          "heading:astronomy",
          "heading:space"
        ],
        "contentLengthBytes": 1045,
        "wordCount": 82,
        "statusCode": 200,
        "fetchTimeMs": 38,
        "processedAt": "2026-09-24T04:34:52.335Z",
        "chunkId": "chunk-002",
        "retryCount": 0
      }
    ]
  },
  {
    "chunkId": "chunk-003",
    "filename": "chunk-003.json",
    "documentCount": 6,
    "totalBytes": 5913,
    "createdAt": "2026-09-24T04:34:52.824Z",
    "documents": [
      {
        "id": "doc-nature_com-83mxuw",
        "url": "https://www.nature.com/articles/d41586-quantum-computing",
        "canonicalUrl": "https://www.nature.com/articles/d41586-quantum-computing",
        "domain": "nature.com",
        "title": "Quantum Computing Milestones and Coherence Times – Nature Science",
        "description": "Peer-reviewed research into superconducting qubits, quantum error correction, and quantum physics coherence times in cryogenic physics laboratories.",
        "headings": {
          "h1": [
            "Breakthroughs in Quantum Physics and Superconducting Qubits"
          ],
          "h2": [
            "Cryogenic Physics Experiments"
          ],
          "h3": []
        },
        "mainText": "Breakthroughs in Quantum Physics and Superconducting Qubits\n\nPhysicists and quantum researchers have demonstrated unprecedented coherence times in superconducting circuits, bringing fault-tolerant quantum algorithms closer to physical reality.\n\nCryogenic Physics Experiments\n\nOperating dilution refrigerators at temperatures below 15 millikelvin shields delicate quantum superposition states from thermal noise and electromagnetic interference.",
        "language": "en",
        "category": "Science",
        "categoryConfidence": 0.76,
        "categorySignals": [
          "domain:nature.com",
          "title:science",
          "title:quantum",
          "heading:physics",
          "heading:quantum",
          "desc:physics",
          "desc:quantum",
          "desc:research",
          "desc:peer-reviewed",
          "body:physics(2)"
        ],
        "contentLengthBytes": 965,
        "wordCount": 49,
        "statusCode": 200,
        "fetchTimeMs": 21,
        "processedAt": "2026-09-24T04:34:52.357Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      },
      {
        "id": "doc-khanacademy_org-xn2tig",
        "url": "https://www.khanacademy.org/math/calculus-1",
        "canonicalUrl": "https://www.khanacademy.org/math/calculus-1",
        "domain": "khanacademy.org",
        "title": "Calculus 1 Course & Practice Lessons | Khan Academy Education",
        "description": "Learn Calculus 1 with free interactive video lectures, practice exercises, syllabus guides, and student quizzes covering limits, derivatives, and integrals.",
        "headings": {
          "h1": [
            "Calculus 1 Curriculum and Student Coursework"
          ],
          "h2": [
            "Course Syllabus Modules",
            "Interactive Student Practice"
          ],
          "h3": []
        },
        "mainText": "Calculus 1 Curriculum and Student Coursework\n\nWelcome to the Khan Academy Calculus 1 education course! Designed for high school and university undergraduate students preparing for AP exams and college STEM degrees.\n\nCourse Syllabus Modules\n\nModule 1 covers limits and continuity, Module 2 introduces differentiation rules, and Module 3 applies derivatives to optimization and physics problems.\n\nInteractive Student Practice\n\nEach unit includes auto-graded quizzes and detailed step-by-step tutoring solutions to help students master fundamental mathematical concepts.",
        "language": "en",
        "category": "Education",
        "categoryConfidence": 0.88,
        "categorySignals": [
          "domain:khanacademy.org",
          "title:education",
          "title:course",
          "title:academy",
          "title_phrase:khan academy",
          "heading:course",
          "heading:student",
          "heading:syllabus",
          "heading:curriculum",
          "desc:student"
        ],
        "contentLengthBytes": 1099,
        "wordCount": 75,
        "statusCode": 200,
        "fetchTimeMs": 39,
        "processedAt": "2026-09-24T04:34:52.396Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      },
      {
        "id": "doc-ocw_mit_edu-8tzz7r",
        "url": "https://ocw.mit.edu/courses/intro-to-algorithms/",
        "canonicalUrl": "https://ocw.mit.edu/courses/intro-to-algorithms/",
        "domain": "ocw.mit.edu",
        "title": "Introduction to Algorithms | MIT OpenCourseWare Free Education",
        "description": "Undergraduate MIT computer science curriculum featuring professor lecture notes, exam problems, syllabus, and study materials for algorithm analysis.",
        "headings": {
          "h1": [
            "MIT Course 6.006: Introduction to Algorithms"
          ],
          "h2": [
            "Professor Lecture Series"
          ],
          "h3": []
        },
        "mainText": "MIT Course 6.006: Introduction to Algorithms\n\nThis undergraduate college course teaches algorithmic design, time complexity analysis (Big-O notation), dynamic programming, divide-and-conquer, and graph algorithms.\n\nProfessor Lecture Series\n\nTaught by leading academic professors in the MIT Department of Electrical Engineering and Computer Science.",
        "language": "en",
        "category": "Education",
        "categoryConfidence": 0.82,
        "categorySignals": [
          "domain:.edu",
          "domain:mit.edu",
          "url_pattern:\\/course",
          "title:education",
          "heading:course",
          "heading:lecture",
          "heading:professor",
          "desc:syllabus",
          "desc:lecture",
          "desc:professor"
        ],
        "contentLengthBytes": 857,
        "wordCount": 42,
        "statusCode": 200,
        "fetchTimeMs": 24,
        "processedAt": "2026-09-24T04:34:52.423Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      },
      {
        "id": "doc-reuters_com-olyz9l",
        "url": "https://www.reuters.com/world/global-climate-summit-accord/",
        "canonicalUrl": "https://www.reuters.com/world/global-climate-summit-accord/",
        "domain": "reuters.com",
        "title": "Global Climate Summit Reaches Historic Clean Energy Accord – Reuters News",
        "description": "Breaking international news: Diplomats and world leaders agree to accelerate renewable energy deployment and carbon reduction targets at global summit.",
        "headings": {
          "h1": [
            "Delegates Reach Landmark Global Energy Accord"
          ],
          "h2": [
            "Summit Spokesperson Briefing"
          ],
          "h3": []
        },
        "mainText": "Delegates Reach Landmark Global Energy Accord\n\nGENEVA (Reuters) — Diplomats and government delegations concluded round-the-clock negotiations on Tuesday, signing a comprehensive multilateral agreement to phase down fossil fuels and double international clean energy investments by 2035.\n\nSummit Spokesperson Briefing\n\nA spokesperson for the summit announced that 142 nations approved the binding communique following bilateral compromise between emerging and developed economies.",
        "language": "en",
        "category": "News",
        "categoryConfidence": 0.8,
        "categorySignals": [
          "domain:reuters.com",
          "url_pattern:\\/world\\/",
          "title:news",
          "heading:spokesperson",
          "desc:news",
          "desc:breaking",
          "body:spokesperson(2)"
        ],
        "contentLengthBytes": 1022,
        "wordCount": 60,
        "statusCode": 200,
        "fetchTimeMs": 31,
        "processedAt": "2026-09-24T04:34:52.454Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      },
      {
        "id": "doc-bloomberg_com-k15cqw",
        "url": "https://www.bloomberg.com/news/articles/global-markets-rally",
        "canonicalUrl": "https://www.bloomberg.com/news/articles/global-markets-rally",
        "domain": "bloomberg.com",
        "title": "Global Stock Markets Rally Following Quarterly Earnings and Rate Forecast – Bloomberg",
        "description": "Financial markets surge as corporate enterprise earnings beat quarterly expectations and central bank inflation forecasts indicate monetary easing.",
        "headings": {
          "h1": [
            "Stock Indices Surge on Strong Corporate Earnings and Economic Data"
          ],
          "h2": [
            "Corporate Revenue and Valuation Multiples"
          ],
          "h3": []
        },
        "mainText": "Stock Indices Surge on Strong Corporate Earnings and Economic Data\n\nWall Street equities and European markets traded higher on Wednesday as quarterly corporate profit margins surpassed consensus analyst estimates, buoyed by enterprise software demand and cooling consumer price inflation.\n\nCorporate Revenue and Valuation Multiples\n\nVenture capital investments and initial public offerings rebounded sharply, while treasury yields stabilized across benchmark ten-year bonds.",
        "language": "en",
        "category": "Business",
        "categoryConfidence": 0.77,
        "categorySignals": [
          "domain:bloomberg.com",
          "title:earnings",
          "title:quarterly",
          "heading:revenue",
          "heading:earnings",
          "heading:valuation",
          "heading:corporate",
          "desc:enterprise",
          "desc:earnings",
          "desc:inflation"
        ],
        "contentLengthBytes": 1018,
        "wordCount": 61,
        "statusCode": 200,
        "fetchTimeMs": 25,
        "processedAt": "2026-09-24T04:34:52.480Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      },
      {
        "id": "doc-espn_com-ne6li7",
        "url": "https://www.espn.com/football/fifa-world-cup-qualifiers",
        "canonicalUrl": "https://www.espn.com/football/fifa-world-cup-qualifiers",
        "domain": "espn.com",
        "title": "FIFA World Cup Qualifiers Scores and Match Highlights – ESPN Sports",
        "description": "Get live match scores, standings, team results, and player statistics from the international FIFA World Cup championship qualification rounds.",
        "headings": {
          "h1": [
            "International Football World Cup Qualifiers Matchday Report"
          ],
          "h2": [
            "Head Coach Post-Match Press Conference"
          ],
          "h3": []
        },
        "mainText": "International Football World Cup Qualifiers Matchday Report\n\nNational teams competed in decisive tournament matches across three continents on Tuesday evening, with stunning goals in stoppage time reshaping group standings.\n\nHead Coach Post-Match Press Conference\n\nThe manager praised the squad's defensive discipline and athletic endurance after holding their rivals to a crucial away draw in front of 68,000 spectators in the stadium.",
        "language": "en",
        "category": "Sports",
        "categoryConfidence": 0.81,
        "categorySignals": [
          "domain:espn.com",
          "url_pattern:\\/football",
          "title:sports",
          "title:match",
          "title:fifa",
          "heading:football",
          "heading:coach",
          "desc:championship",
          "desc:match",
          "desc:fifa"
        ],
        "contentLengthBytes": 952,
        "wordCount": 61,
        "statusCode": 200,
        "fetchTimeMs": 29,
        "processedAt": "2026-09-24T04:34:52.510Z",
        "chunkId": "chunk-003",
        "retryCount": 0
      }
    ]
  },
  {
    "chunkId": "chunk-004",
    "filename": "chunk-004.json",
    "documentCount": 5,
    "totalBytes": 4997,
    "createdAt": "2026-09-24T04:34:52.824Z",
    "documents": [
      {
        "id": "doc-variety_com-c8488j",
        "url": "https://variety.com/feature/cannes-film-festival-screenings",
        "canonicalUrl": "https://variety.com/feature/cannes-film-festival-screenings",
        "domain": "variety.com",
        "title": "Cannes Film Festival Premiere Reviews and Box Office Preview – Variety Entertainment",
        "description": "In-depth coverage of cinematic world premieres, director interviews, festival awards, and Hollywood box office projections from the Cannes Croisette.",
        "headings": {
          "h1": [
            "Cannes Film Festival Red Carpet and Premiere Highlights"
          ],
          "h2": [
            "Palme d'Or Contenders and Director Spotlights"
          ],
          "h3": []
        },
        "mainText": "Cannes Film Festival Red Carpet and Premiere Highlights\n\nAcclaimed directors and international actors gathered on the French Riviera as jury members previewed competing feature films and documentary cinema entries.\n\nPalme d'Or Contenders and Director Spotlights\n\nCritics gave standing ovations to breakthrough theatrical indie dramas and high-concept science fiction thrillers eyeing global streaming releases.",
        "language": "en",
        "category": "Entertainment",
        "categoryConfidence": 0.86,
        "categorySignals": [
          "domain:variety.com",
          "title:entertainment",
          "title:film",
          "title_phrase:box office",
          "title:festival",
          "heading:film",
          "heading:director",
          "heading:festival",
          "desc:director",
          "desc:hollywood"
        ],
        "contentLengthBytes": 954,
        "wordCount": 53,
        "statusCode": 200,
        "fetchTimeMs": 30,
        "processedAt": "2026-09-24T04:34:52.540Z",
        "chunkId": "chunk-004",
        "retryCount": 0
      },
      {
        "id": "doc-who_int-vqpxzm",
        "url": "https://www.who.int/news-room/fact-sheets/detail/cardiovascular-diseases",
        "canonicalUrl": "https://www.who.int/news-room/fact-sheets/detail/cardiovascular-diseases",
        "domain": "who.int",
        "title": "Cardiovascular Diseases: Prevention and Clinical Guidelines – WHO Health",
        "description": "World Health Organization fact sheet on cardiovascular health, hypertension symptoms, clinical diagnosis, lifestyle therapy, and preventive medicine.",
        "headings": {
          "h1": [
            "Cardiovascular Health, Disease Prevention, and Clinical Care"
          ],
          "h2": [
            "Clinical Diagnosis & Medical Therapy"
          ],
          "h3": []
        },
        "mainText": "Cardiovascular Health, Disease Prevention, and Clinical Care\n\nCardiovascular diseases are the leading cause of mortality globally. Most cardiovascular conditions can be prevented by addressing behavioral risk factors such as physical inactivity, tobacco use, and unhealthy diet.\n\nClinical Diagnosis & Medical Therapy\n\nEarly detection through blood pressure screening, cholesterol management, and evidence-based pharmacotherapy reduces hospitalizations and coronary complications.",
        "language": "en",
        "category": "Health",
        "categoryConfidence": 0.88,
        "categorySignals": [
          "domain:who.int",
          "title:health",
          "title:clinical",
          "heading:health",
          "heading:medical",
          "heading:clinical",
          "heading:disease",
          "heading:therapy",
          "heading:diagnosis",
          "desc:health"
        ],
        "contentLengthBytes": 1024,
        "wordCount": 57,
        "statusCode": 200,
        "fetchTimeMs": 31,
        "processedAt": "2026-09-24T04:34:52.572Z",
        "chunkId": "chunk-004",
        "retryCount": 0
      },
      {
        "id": "doc-lonelyplanet_com-znu7pv",
        "url": "https://www.lonelyplanet.com/articles/best-sustainable-travel-destinations",
        "canonicalUrl": "https://www.lonelyplanet.com/articles/best-sustainable-travel-destinations",
        "domain": "lonelyplanet.com",
        "title": "Best Sustainable Travel Destinations & Eco-Tourism Itineraries – Lonely Planet Travel",
        "description": "Discover top eco-friendly travel destinations, boutique hotels, scenic train itineraries, and responsible tourism guides for world travelers.",
        "headings": {
          "h1": [
            "Sustainable Travel Guides and Top Vacation Itineraries"
          ],
          "h2": [
            "Booking Flights, Boutique Hotels, and Local Tours"
          ],
          "h3": []
        },
        "mainText": "Sustainable Travel Guides and Top Vacation Itineraries\n\nPlanning your next holiday? From scenic Alpine rail adventures to pristine coastal eco-resorts, explore destination guides that combine unforgettable cultural sightseeing with low-impact exploration.\n\nBooking Flights, Boutique Hotels, and Local Tours\n\nTips on packing light luggage, securing train passes, and immersing in local communities off the beaten tourist path.",
        "language": "en",
        "category": "Travel",
        "categoryConfidence": 0.8,
        "categorySignals": [
          "domain:lonelyplanet.com",
          "title:travel",
          "heading:travel",
          "heading:vacation",
          "desc:travel",
          "desc:tourism"
        ],
        "contentLengthBytes": 977,
        "wordCount": 56,
        "statusCode": 200,
        "fetchTimeMs": 27,
        "processedAt": "2026-09-24T04:34:52.601Z",
        "chunkId": "chunk-004",
        "retryCount": 0
      },
      {
        "id": "doc-en_wikipedia_org-45fc2m",
        "url": "https://en.wikipedia.org/wiki/Portal:Contents",
        "canonicalUrl": "https://en.wikipedia.org/wiki/Portal:Contents",
        "domain": "en.wikipedia.org",
        "title": "Portal: Contents – Wikipedia Reference Directory",
        "description": "General reference portal, category indexes, subject overviews, and broad encyclopedic topic directories across all human knowledge.",
        "headings": {
          "h1": [
            "Wikipedia Knowledge Portal and Reference Directories"
          ],
          "h2": [
            "Subject Overviews and Indexes"
          ],
          "h3": []
        },
        "mainText": "Wikipedia Knowledge Portal and Reference Directories\n\nThis page serves as a master general index and navigation guide to articles, portals, outlines, and topical overviews across the free encyclopedia.\n\nSubject Overviews and Indexes\n\nBrowse general topics categorized by humanities, natural sciences, geography, history, and culture.",
        "language": "en",
        "category": "General",
        "categoryConfidence": 0.87,
        "categorySignals": [
          "domain:wikipedia.org",
          "url_pattern:\\/portal",
          "title:portal",
          "title:directory",
          "title:reference",
          "heading:portal",
          "heading:reference",
          "desc:general",
          "desc:portal",
          "desc:reference"
        ],
        "contentLengthBytes": 809,
        "wordCount": 44,
        "statusCode": 200,
        "fetchTimeMs": 32,
        "processedAt": "2026-09-24T04:34:52.634Z",
        "chunkId": "chunk-004",
        "retryCount": 0
      },
      {
        "id": "doc-en_wikipedia_org-5qiwq8",
        "url": "https://en.wikipedia.org/wiki/Okapi_BM25",
        "canonicalUrl": "https://en.wikipedia.org/wiki/Okapi_BM25",
        "domain": "en.wikipedia.org",
        "title": "Okapi BM25 – Wikipedia, the free encyclopedia",
        "description": "In information retrieval, Okapi BM25 is a probabilistic ranking function used by search engines to estimate the relevance of documents to a given search query.",
        "headings": {
          "h1": [
            "Okapi BM25 Information Retrieval"
          ],
          "h2": [
            "The Ranking Function Formula",
            "Search Engine Implementations"
          ],
          "h3": []
        },
        "mainText": "Okapi BM25 Information Retrieval\n\nOkapi BM25 (BM is an abbreviation of Best Matching) is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document, regardless of their inter-relationship.\n\nThe Ranking Function Formula\n\nGiven a query Q containing keywords q1 through qn, the BM25 score of a document D is evaluated using inverse document frequency (IDF), term frequency saturation controlled by parameter k1, and document length normalization parameterized by b.\n\nSearch Engine Implementations\n\nWidely adopted by modern search systems including Lucene, Elasticsearch, and NexVora for fast, mathematically sound keyword scoring without black-box auction bias.",
        "language": "en",
        "category": "Technology",
        "categoryConfidence": 0.53,
        "categorySignals": [
          "title:bm25",
          "heading:bm25",
          "heading_phrase:search engine",
          "desc:bm25",
          "desc_phrase:search engine",
          "body:bm25(3)"
        ],
        "contentLengthBytes": 1233,
        "wordCount": 102,
        "statusCode": 200,
        "fetchTimeMs": 21,
        "processedAt": "2026-09-24T04:34:52.824Z",
        "chunkId": "chunk-004",
        "retryCount": 0
      }
    ]
  }
];

export const PRECOMPILED_REPORT: ProcessingReport = {
  "reportId": "report-1790224492825",
  "generatedAt": "2026-09-24T04:34:52.825Z",
  "deploymentOrigin": "https://ais-dev-5k4ivhpfmtfni6oilgnbeq-361676640170.asia-southeast1.run.app",
  "summary": {
    "totalUrlsQueued": 57,
    "successfullyProcessed": 23,
    "failedUrlsCount": 2,
    "skippedRobotsCount": 0,
    "duplicateUrlsIgnored": 1,
    "totalChunksGenerated": 4,
    "totalExtractedBytes": 21869,
    "averageFetchTimeMs": 30
  },
  "categoryDistribution": {
    "Education": 2,
    "Programming": 7,
    "Technology": 5,
    "Science": 2,
    "News": 1,
    "Business": 1,
    "Sports": 1,
    "Entertainment": 1,
    "Health": 1,
    "Travel": 1,
    "General": 1
  },
  "chunks": [
    {
      "chunkId": "chunk-001",
      "path": "generated/documents/chunk-001.json",
      "count": 6
    },
    {
      "chunkId": "chunk-002",
      "path": "generated/documents/chunk-002.json",
      "count": 6
    },
    {
      "chunkId": "chunk-003",
      "path": "generated/documents/chunk-003.json",
      "count": 6
    },
    {
      "chunkId": "chunk-004",
      "path": "generated/documents/chunk-004.json",
      "count": 5
    }
  ],
  "failedUrls": [
    {
      "url": "https://en.wikipedia.org/trap/crawler-honeypot",
      "domain": "en.wikipedia.org",
      "errorReason": "Path matches standard sensitive/admin route blocklist",
      "failedAt": "2026-09-24T04:34:52.824Z",
      "attemptsMade": 1,
      "willRetry": false
    },
    {
      "url": "httpx://invalid-protocol-test.com/bad^url",
      "domain": "unknown",
      "errorReason": "Malformed or invalid HTTP/HTTPS URL format",
      "failedAt": "2026-09-24T04:34:52.824Z",
      "attemptsMade": 1,
      "willRetry": false
    }
  ]
};

export const PRECOMPILED_FAILED_URLS: FailedUrlRecord[] = [
  {
    "url": "https://en.wikipedia.org/trap/crawler-honeypot",
    "domain": "en.wikipedia.org",
    "errorReason": "Path matches standard sensitive/admin route blocklist",
    "failedAt": "2026-09-24T04:34:52.824Z",
    "attemptsMade": 1,
    "willRetry": false
  },
  {
    "url": "httpx://invalid-protocol-test.com/bad^url",
    "domain": "unknown",
    "errorReason": "Malformed or invalid HTTP/HTTPS URL format",
    "failedAt": "2026-09-24T04:34:52.824Z",
    "attemptsMade": 1,
    "willRetry": false
  }
];

export const PRECOMPILED_CATEGORIES: Record<string, CategoryIndexChunk> = {
  "education": {
    "category": "Education",
    "documentCount": 2,
    "updatedAt": "2026-09-24T04:34:52.423Z",
    "documentIds": [
      "doc-khanacademy_org-xn2tig",
      "doc-ocw_mit_edu-8tzz7r"
    ],
    "items": [
      {
        "id": "doc-khanacademy_org-xn2tig",
        "title": "Calculus 1 Course & Practice Lessons | Khan Academy Education",
        "canonicalUrl": "https://www.khanacademy.org/math/calculus-1",
        "domain": "khanacademy.org",
        "description": "Learn Calculus 1 with free interactive video lectures, practice exercises, syllabus guides, and student quizzes covering limits, derivatives, and integrals.",
        "confidence": 0.88
      },
      {
        "id": "doc-ocw_mit_edu-8tzz7r",
        "title": "Introduction to Algorithms | MIT OpenCourseWare Free Education",
        "canonicalUrl": "https://ocw.mit.edu/courses/intro-to-algorithms/",
        "domain": "ocw.mit.edu",
        "description": "Undergraduate MIT computer science curriculum featuring professor lecture notes, exam problems, syllabus, and study materials for algorithm analysis.",
        "confidence": 0.82
      }
    ]
  },
  "programming": {
    "category": "Programming",
    "documentCount": 7,
    "updatedAt": "2026-09-24T04:34:52.296Z",
    "documentIds": [
      "doc-developer_mozilla_org-u8z5d0",
      "doc-react_dev-30482j",
      "doc-rust_lang_org-tjztg8",
      "doc-bun_sh-cddiid",
      "doc-vite_dev-s4xs6s",
      "doc-tailwindcss_com-0cja4g",
      "doc-signal_org-6kh80a"
    ],
    "items": [
      {
        "id": "doc-developer_mozilla_org-u8z5d0",
        "title": "JavaScript | MDN Web Docs",
        "canonicalUrl": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
        "domain": "developer.mozilla.org",
        "description": "JavaScript (JS) is a lightweight interpreted or just-in-time compiled programming language with first-class functions for web development.",
        "confidence": 0.84
      },
      {
        "id": "doc-react_dev-30482j",
        "title": "React 19 is now stable – React Official Blog",
        "canonicalUrl": "https://react.dev/blog/2024/12/05/react-19",
        "domain": "react.dev",
        "description": "React 19 is now available on npm! Featuring Actions, Server Components, Document Metadata hooks, and asset preloading for frontend developers.",
        "confidence": 0.81
      },
      {
        "id": "doc-rust_lang_org-tjztg8",
        "title": "Learn Rust – Rust Programming Language",
        "canonicalUrl": "https://www.rust-lang.org/learn",
        "domain": "rust-lang.org",
        "description": "Empowering everyone to build reliable and efficient software. Learn Rust through interactive tutorials, the Rust Book, and compiler borrow checker guides.",
        "confidence": 0.65
      },
      {
        "id": "doc-bun_sh-cddiid",
        "title": "Bun Documentation – Fast JavaScript Runtime & Package Manager",
        "canonicalUrl": "https://bun.sh/docs",
        "domain": "bun.sh",
        "description": "Bun is an all-in-one JavaScript runtime, bundler, test runner, and package manager written in Zig with native speed and Node.js compatibility.",
        "confidence": 0.89
      },
      {
        "id": "doc-vite_dev-s4xs6s",
        "title": "Getting Started | Vite Next Generation Frontend Tooling",
        "canonicalUrl": "https://vite.dev/guide/",
        "domain": "vite.dev",
        "description": "Vite is a modern build tool that aims to provide a faster and leaner development experience for modern web projects using native ES modules.",
        "confidence": 0.77
      },
      {
        "id": "doc-tailwindcss_com-0cja4g",
        "title": "Upgrade Guide to Tailwind CSS v4 – Tailwind Documentation",
        "canonicalUrl": "https://tailwindcss.com/docs/v4-upgrade-guide",
        "domain": "tailwindcss.com",
        "description": "Comprehensive guide for migrating your frontend styles to Tailwind CSS v4 featuring the new high-speed Rust-powered engine and CSS-first configuration.",
        "confidence": 0.45
      },
      {
        "id": "doc-signal_org-6kh80a",
        "title": "The Double Ratchet Algorithm – Signal Cryptographic Protocol",
        "canonicalUrl": "https://signal.org/docs/specifications/doubleratchet/",
        "domain": "signal.org",
        "description": "Cryptographic specification of the Double Ratchet Algorithm: providing end-to-end encryption with forward secrecy and break-in recovery for messaging protocols.",
        "confidence": 0.42
      }
    ]
  },
  "technology": {
    "category": "Technology",
    "documentCount": 5,
    "updatedAt": "2026-09-24T04:34:52.824Z",
    "documentIds": [
      "doc-github_com-2sioca",
      "doc-sqlite_org-0n5f59",
      "doc-kubernetes_io-n9zmsd",
      "doc-docs_docker_com-20mfff",
      "doc-en_wikipedia_org-5qiwq8"
    ],
    "items": [
      {
        "id": "doc-github_com-2sioca",
        "title": "torvalds/linux: Linux kernel source tree – GitHub",
        "canonicalUrl": "https://github.com/torvalds/linux",
        "domain": "github.com",
        "description": "Linux kernel source tree maintained by Linus Torvalds. The open source monolithic operating system kernel powering cloud servers, supercomputers, and mobile devices.",
        "confidence": 0.65
      },
      {
        "id": "doc-sqlite_org-0n5f59",
        "title": "Architecture of SQLite – In-Process SQL Database Engine",
        "canonicalUrl": "https://sqlite.org/arch.html",
        "domain": "sqlite.org",
        "description": "Technical architecture and internal subsystems of SQLite: tokenizer, parser, code generator, virtual machine (VDBE), B-Tree, pager, and OS interface.",
        "confidence": 0.8
      },
      {
        "id": "doc-kubernetes_io-n9zmsd",
        "title": "What is Kubernetes? | Kubernetes Cloud Infrastructure",
        "canonicalUrl": "https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/",
        "domain": "kubernetes.io",
        "description": "Kubernetes is an open-source container orchestration system for automating software deployment, scaling, and management of containerized applications.",
        "confidence": 0.8
      },
      {
        "id": "doc-docs_docker_com-20mfff",
        "title": "Docker Overview | Containerization Platform Architecture",
        "canonicalUrl": "https://docs.docker.com/get-started/overview/",
        "domain": "docs.docker.com",
        "description": "Docker is an open platform for developing, shipping, and running applications using OS-level containerization for predictable environments.",
        "confidence": 0.66
      },
      {
        "id": "doc-en_wikipedia_org-5qiwq8",
        "title": "Okapi BM25 – Wikipedia, the free encyclopedia",
        "canonicalUrl": "https://en.wikipedia.org/wiki/Okapi_BM25",
        "domain": "en.wikipedia.org",
        "description": "In information retrieval, Okapi BM25 is a probabilistic ranking function used by search engines to estimate the relevance of documents to a given search query.",
        "confidence": 0.53
      }
    ]
  },
  "science": {
    "category": "Science",
    "documentCount": 2,
    "updatedAt": "2026-09-24T04:34:52.357Z",
    "documentIds": [
      "doc-webb_nasa_gov-z5ha8c",
      "doc-nature_com-83mxuw"
    ],
    "items": [
      {
        "id": "doc-webb_nasa_gov-z5ha8c",
        "title": "Science Overview – James Webb Space Telescope – NASA",
        "canonicalUrl": "https://webb.nasa.gov/content/science/overview.html",
        "domain": "webb.nasa.gov",
        "description": "Explore the scientific mission of NASA",
        "confidence": 0.88
      },
      {
        "id": "doc-nature_com-83mxuw",
        "title": "Quantum Computing Milestones and Coherence Times – Nature Science",
        "canonicalUrl": "https://www.nature.com/articles/d41586-quantum-computing",
        "domain": "nature.com",
        "description": "Peer-reviewed research into superconducting qubits, quantum error correction, and quantum physics coherence times in cryogenic physics laboratories.",
        "confidence": 0.76
      }
    ]
  },
  "news": {
    "category": "News",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.454Z",
    "documentIds": [
      "doc-reuters_com-olyz9l"
    ],
    "items": [
      {
        "id": "doc-reuters_com-olyz9l",
        "title": "Global Climate Summit Reaches Historic Clean Energy Accord – Reuters News",
        "canonicalUrl": "https://www.reuters.com/world/global-climate-summit-accord/",
        "domain": "reuters.com",
        "description": "Breaking international news: Diplomats and world leaders agree to accelerate renewable energy deployment and carbon reduction targets at global summit.",
        "confidence": 0.8
      }
    ]
  },
  "business": {
    "category": "Business",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.480Z",
    "documentIds": [
      "doc-bloomberg_com-k15cqw"
    ],
    "items": [
      {
        "id": "doc-bloomberg_com-k15cqw",
        "title": "Global Stock Markets Rally Following Quarterly Earnings and Rate Forecast – Bloomberg",
        "canonicalUrl": "https://www.bloomberg.com/news/articles/global-markets-rally",
        "domain": "bloomberg.com",
        "description": "Financial markets surge as corporate enterprise earnings beat quarterly expectations and central bank inflation forecasts indicate monetary easing.",
        "confidence": 0.77
      }
    ]
  },
  "sports": {
    "category": "Sports",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.510Z",
    "documentIds": [
      "doc-espn_com-ne6li7"
    ],
    "items": [
      {
        "id": "doc-espn_com-ne6li7",
        "title": "FIFA World Cup Qualifiers Scores and Match Highlights – ESPN Sports",
        "canonicalUrl": "https://www.espn.com/football/fifa-world-cup-qualifiers",
        "domain": "espn.com",
        "description": "Get live match scores, standings, team results, and player statistics from the international FIFA World Cup championship qualification rounds.",
        "confidence": 0.81
      }
    ]
  },
  "entertainment": {
    "category": "Entertainment",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.541Z",
    "documentIds": [
      "doc-variety_com-c8488j"
    ],
    "items": [
      {
        "id": "doc-variety_com-c8488j",
        "title": "Cannes Film Festival Premiere Reviews and Box Office Preview – Variety Entertainment",
        "canonicalUrl": "https://variety.com/feature/cannes-film-festival-screenings",
        "domain": "variety.com",
        "description": "In-depth coverage of cinematic world premieres, director interviews, festival awards, and Hollywood box office projections from the Cannes Croisette.",
        "confidence": 0.86
      }
    ]
  },
  "health": {
    "category": "Health",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.573Z",
    "documentIds": [
      "doc-who_int-vqpxzm"
    ],
    "items": [
      {
        "id": "doc-who_int-vqpxzm",
        "title": "Cardiovascular Diseases: Prevention and Clinical Guidelines – WHO Health",
        "canonicalUrl": "https://www.who.int/news-room/fact-sheets/detail/cardiovascular-diseases",
        "domain": "who.int",
        "description": "World Health Organization fact sheet on cardiovascular health, hypertension symptoms, clinical diagnosis, lifestyle therapy, and preventive medicine.",
        "confidence": 0.88
      }
    ]
  },
  "travel": {
    "category": "Travel",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.601Z",
    "documentIds": [
      "doc-lonelyplanet_com-znu7pv"
    ],
    "items": [
      {
        "id": "doc-lonelyplanet_com-znu7pv",
        "title": "Best Sustainable Travel Destinations & Eco-Tourism Itineraries – Lonely Planet Travel",
        "canonicalUrl": "https://www.lonelyplanet.com/articles/best-sustainable-travel-destinations",
        "domain": "lonelyplanet.com",
        "description": "Discover top eco-friendly travel destinations, boutique hotels, scenic train itineraries, and responsible tourism guides for world travelers.",
        "confidence": 0.8
      }
    ]
  },
  "general": {
    "category": "General",
    "documentCount": 1,
    "updatedAt": "2026-09-24T04:34:52.634Z",
    "documentIds": [
      "doc-en_wikipedia_org-45fc2m"
    ],
    "items": [
      {
        "id": "doc-en_wikipedia_org-45fc2m",
        "title": "Portal: Contents – Wikipedia Reference Directory",
        "canonicalUrl": "https://en.wikipedia.org/wiki/Portal:Contents",
        "domain": "en.wikipedia.org",
        "description": "General reference portal, category indexes, subject overviews, and broad encyclopedic topic directories across all human knowledge.",
        "confidence": 0.87
      }
    ]
  }
};
